name: TNTRun
version: '${project.version}'
main: me.abdulhamit.tntrun.TNTRun
api-version: '1.20'
commands:
  startmanually:
    permission: tntrun.startmanually
    usage: /startmanually
    permission-message: §4You do not have permission to execute this command!
    description: starts the tnt run manually
    aliases: [startm]
  toggleparticipant:
    usage: /toggle participant
    description: toggles participant mode
    aliases: [toggp, togglep, tparticipant]
  width:
    permission: tntrun.setwidth
    usage: /width
    permission-message: §4You don't have the permission to execute this command!
    description: sets the width of the map!
    aliases: [setwidth]
  tntrain:
    usage: /tntrain
    permission: tntrun.tntrain
    permission-message: §4You dont have permission to execute this command!
    description: make tnt rain
  stats:
    usage: /stats player
    description: get the stats of a player
  reloadannouncements:
    usage: /reloadannouncements
    description: reloads announcements
    aliases: ["reloada", "reloadann"]
    permission: tntrun.reloadannouncements
    permission-message: §4You do not have permission to use this command!
  setstat:
    usage: /setstat <player> <statistic> <value>
    permission: tntrun.setstat
    permission-message: §4You do not have enough permission to use this command